Dark mode support
w3c/tr-design pull request #184
Opened 2020-01-03 10:47 UTC by jakubklimek

Continuation of https://github.com/w3c/respec/issues/2651 - This is a proposal for adding dark mode support to W3C documents using the `@media (prefers-color-scheme: dark)` CSS media query and CSS variables. It is currently in use in our data standards in Czechia, which, in addition, use our [respec fork](https://github.com/opendata-mvcr/respec) as Respec also adds some CSS. You can see the result (with dark mode enabled) e.g. here: https://ofn.gov.cz/rozhraní-katalogů-otevřených-dat/2019-04-04/

Clearly, this will work only with [browsers supporting the CSS query](https://caniuse.com/#feat=prefers-color-scheme) and in the current state, it breaks support mainly for IE 11, which [does not support CSS variables](https://caniuse.com/#feat=css-variables).

2020-01-03 19:01 UTC, plehegar commented
@tabatkins , can you also confirm that this update is ok for bikeshed-generated documents?

2020-01-03 20:11 UTC, sidvishnoi commented on src/base.css
> +  --issue-marker-color: #AE1E1;
```suggestion
  --issue-marker-color: #AE1E1E;
```

2020-01-04 10:38 UTC, ZoeBijl commented
Thank you for this! Is there a way in which we can achieve this without dropping support for older browsers?

2020-01-04 12:55 UTC, sidvishnoi commented
> Is there a way in which we can achieve this without dropping support for older browsers?

This should work.

``` css
:root {
	--heading-color: #005A9C;
}
h1, h2, h3 {
	color: #005A9C;              /* keep this. fallback for older browsers */
	color: var(--heading-color); /* for new browsers */
}
```

2020-01-04 16:00 UTC, dbaron commented
The addition of dark mode support probably means that any TR publications with their own custom styling involving colors or backgrounds should be reviewed to check that the custom styling also works correctly in dark mode.  (How many TR publications have custom styling that involves colors or backgrounds?)

Is it correct that changes to the stylesheets only apply to new TR publications going forward, and not to existing ones?

2020-01-05 13:04 UTC, saschanaz commented
> Is it correct that changes to the stylesheets only apply to new TR publications going forward, and not to existing ones?

AFAIK ReSpec always uses `"https://www.w3.org/StyleSheets/TR/2016/base.css"`, so any changes should affect existing ReSpec-based specifications.

2020-01-05 13:19 UTC, saschanaz commented
> Thank you for this! Is there a way in which we can achieve this without dropping support for older browsers?

I would keep the current style and add overrides without defining custom properties.

```css
/* existing ones, keep them intact */
body {
	background: white top left fixed no-repeat;
}

#toc-nav > a {
	background-color: white;
}

/* dark mode */
@media (prefers-color-scheme: dark) {
	body {
		background: rgb(24, 26, 27);
	}

	#toc-nav > a {
		background-color: rgb(24, 26, 27);
	}
}

/* alternatively, if we prefer custom properties */
@media (prefers-color-scheme: dark) {
	:root {
		--main-bg-color: rgb(24, 26, 27);
	}

	body {
		color: var(--main-bg-color);
	}

	#toc-nav > a {
		background-color: var(--main-bg-color);
	}
}
```

2020-01-06 03:15 UTC, frivoal commented
While this looks nice, lots of of specs use some amount of custom styling in examples, and/or include pictures that assume a light / white background. Even for new publications, it can be a bit tricky, as having to re-write all the examples in the spec before you can push an update doesn't sound like fun. Rolling this out needs a strategy to deal with those.
* Maybe don't apply this stylesheet to old specs?
* Maybe keep all examples and figures in dark-on-light mode (unless something in the source indicates that that example is safe)?
* Maybe have an opt-out for examples and figures, instead of the opt-in as suggested in the previous point?
* Maybe have an opt-in for the whole spec, rather than just for examples and figures?
* …

2020-01-06 03:18 UTC, saschanaz commented
> Maybe don't apply this stylesheet to old specs?

How about publishing a new dark-mode CSS file (as an addition on top of the existing one) so that only new specs can use it?

2020-01-06 05:31 UTC, fantasai commented
Agree with @saschanaz's comments on approach https://github.com/w3c/tr-design/pull/184#issuecomment-570911928 and @frivoal's concerns about custom styles. We're either going to need an opt-in mechanism, or we need to push out the release enough to give WGs time to all update their styles to handle dark mode.

2020-01-06 05:33 UTC, fantasai requested changes
r- until we figure out deployment strategy

2020-01-07 17:34 UTC, tabatkins commented
I'll review this later today; I was already planning on spending today doing this exact work myself. ^_^

One thing I note already, tho: downlevel browsers that don't understand variables are still reasonably common today (>1%). My plan was to keep every single color-using declaration in the spec, and just add the variable-using version after it, so parsing would ensure the spec still looked the same in old browsers.

2020-01-08 01:06 UTC, tabatkins commented
* `--table-cell-hover-bg-color` is not overridden in the dark styles
* The overall page background is not set, so it remains white. ^_^
* I'm *really* not liking the dark-mode Example and Note colors, they need some serious tweaking for aesthetics. Issues aren't quite as bad, but could stand to be aligned with that effort. .def blocks are pretty good.
* I think an `img { background: white; }` rule is needed (in both light and dark mode), so that images using a transparent bg (assumed to be white) remain visible.
* Anything using Bikeshed's syntax highlighting becomes unreadable here, as the (light) unchanged code background clashes with the light dark-mode text. This should be fixable with a `.highlight:not(.idl) { color: black; }` rule for now; I can override that in Bikeshed once I put together dark-mode syntax-highlight colors.
* WebIDL blocks with syntax highlighting are unreadable for a different reason, as they assume they're displayed on the light-blue .def colors, and so all the *dark* syntax-bits are now unreadable. Possible hackable in old specs by making the background light for these blocks, but that's not great.
* Advisement colors are overridden for dark mode, but have identical values, so they're bright *and* unreadable (since they just inherit the page-wide text color).
* I'm not certain *why* all the items in the "Terms defined by reference" index have an inline `color: initial` declaration, but they do, which means they go black in dark mode currently. Currently this is unfixable in Chrome, as we don't *quite* support the `color-scheme` property yet, but also, there should be an `html { color-scheme: light dark; }` rule for browsers that *do* support that property.

-------

Overall, just a few small bugs, and one big aesthetic thing that I think needs reviewing, but the syntax-highlighting thing is pretty bad. I think it's better to give old specs dark-mode styles than to be absolutely safe that everything is perfectly readable, so I support working around the syntax-highlighting issue and letting Bikeshed and ReSpec undo the workaround.

Otherwise looks like a great job.

2020-01-15 21:17 UTC, plehegar commented
In terms of deployment strategy, we could release the update as a 2020 one, ie not changing the 2016 stylesheet, thus we would create https://www.w3.org/StyleSheets/TR/2020/ .

2020-01-16 03:04 UTC, frivoal commented
@plehegar Even that is probably a bit rough on spec editors if the 2020 stylesheet is meant to be applied to all publications created after it goes live itself: editors of a spec that has existed since before that could not update & republish their spec until they have fixed all examples, figures, etc to work well both in light and dark mode. While they should eventually adjust all of that, saying that you can't publish at all until you've "fixed" the entire spec is not nice (especially given that until now, there was nothing considered broken to be fixed).

If we allow **new** publications that don't feel ready for the 2020 stylesheet to continue using the 2016 one, then it's not as bad, but that still means you've got to do an "fix all the things" run at some point before you switch to the 2020 one.

One way or another, I think we need to have a stylesheet that has dark mode AND can be used with specs that aren't designed for dark mode without breaking examples, figures, etc. It doesn't have to be ideal, but it has to work. From there, editors can progressively fix up figures and the like to be better suited to dark mode.

2020-01-16 21:24 UTC, tabatkins commented
My suggestion to just add a `background:white` to all svg/img in the spec should fix that problem generally.

2020-01-21 02:46 UTC, marcoscaceres commented
Deferring review based on feedback, but generally supportive of what is being proposed and that we need an opt-in strategy.

2020-03-20 23:59 UTC, tabatkins commented
This has gone without updates for two months. If no one objects, I'll take it over and finish it sometime next week.

2020-03-21 00:18 UTC, tabatkins commented
> I'm not certain why all the items in the "Terms defined by reference" index have an inline color: initial declaration,

Ah, diagnosed this, it was me hacking around an overly-broad selector in base.css. Blocked on <https://github.com/w3c/tr-design/pull/188> getting merged.

2020-09-08 18:11 UTC, closed without merging