Add template for images for invisible characters
w3c/tr-design pull request #341
Opened 2023-10-02 22:59 UTC by aphillips

Fixes #340.

- Adds the text about using an `img` for invisible/whitespace characters
- Adds the corresponding style
- Adds an image for U+00A0, used in the example

2023-10-02 23:00 UTC, aphillips commented
@fantasai @xfq @r12a Please check this.

2023-10-03 06:44 UTC, deniak requested changes

2023-10-03 06:44 UTC, deniak commented on src/base.css
> +        font-family: Arial, monospace;
Please use tabs for indentation.

2023-10-03 06:44 UTC, deniak commented on src/README.html
> +</aside>
```suggestion
  <aside class="example" title="Example of a character reference with an image">
    <p>Filling in the above template like this:</p>

    <pre>
<!-- -->&lt;span class="codepoint" translate="no">&lt;img alt="NBSP" src="images/00A0.png">
<!-- -->&lt;code class="uname">U+00A0 NO-BREAK SPACE&lt;/code>&lt;/span>
    </pre>

    <p>Produces output in the page like this: <span class="codepoint" translate="no">
	  <img alt="NBSP" src="images/00A0.png"><code class="uname">U+00A0 NO-BREAK SPACE</code></span>.</p>
  </aside>
```

2023-10-03 14:47 UTC, aphillips commented on src/base.css
> +        font-family: Arial, monospace;
Done

2023-10-05 14:41 UTC, r12a approved these changes

2023-10-05 14:53 UTC, deniak approved these changes

2023-10-05 14:53 UTC, merged